### ISSUE TITLE
插件接口每条输入有单独的输出结果标志本次执行是否成功

### ISSUE THREAD

**Issue by brankbao** [WeBankPartners/wecube-plugins-qcloud#109]
**描述您的需求**  
对于多条记录的请求，对每条记录的返回值中单独添加成功和失败的结果，方便区分哪些记录执行成功，哪些记录执行失败

**预期行为**  
对你预期会发生的事情的清晰而简洁的描述。 

**描述您考虑过的替代方案**  
对您考虑的替代解决方案进行清晰而简洁的描述。 

**附加**  
在此添加有关问题的任何其他上下文。

**Comment by TylerTang06** [comment]
done
