### ISSUE TITLE
在wecube上传qcloud插件包报错

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-plugins-qcloud#123]
**描述您遇到的bug**  
在wecube上传qcloud插件包报错
![image](https://user-images.githubusercontent.com/17095701/71139126-44792080-2248-11ea-9196-07665f842b04.png)

**如何重现** 
再现行为的步骤

**预期行为** 
对你预期会发生的事情的清晰而简洁的描述。 

**截图**  
请添加屏幕截图以帮助解释您的问题。 

**附加**  
在此添加有关问题的任何其他上下文。

**Comment by TylerTang06** [comment]
done
