### ISSUE TITLE
qcloud-mysql没有创建（只读从节点和灾备从节点的属性），指定主节点。

### ISSUE THREAD

**Issue by irvinezhao** [WeBankPartners/wecube-plugins-qcloud#125]
**描述您的需求**  
对需求进行清晰而简洁的描述。 

**预期行为**  
对你预期会发生的事情的清晰而简洁的描述。 

**描述您考虑过的替代方案**  
对您考虑的替代解决方案进行清晰而简洁的描述。 

**附加**  
在此添加有关问题的任何其他上下文。

**Comment by brankbao** [comment]
mysql创建时加个InstanceRole，如果是只读实例，加MasterInstanceId参数；MasterRegion，主实例地域信息，购买灾备实例时，该字段必填；RoGroup只读实例参数。购买只读实例时，该参数必传，这个参数先不暴露，实现的时候自己alone

**Comment by brankbao** [comment]
创建mysql只读实例，接口调用成功，但是出来的实例是master实例，不是只读实例
