### ISSUE TITLE
网络组工单-和网络组调接口

### ISSUE THREAD

**Issue by brankbao** [WeBankPartners/wecube-plugins-qcloud#31]
**描述您的需求**  
对需求进行清晰而简洁的描述。 

**预期行为**  
对你预期会发生的事情的清晰而简洁的描述。 

**描述您考虑过的替代方案**  
对您考虑的替代解决方案进行清晰而简洁的描述。 

**附加**  
在此添加有关问题的任何其他上下文。

**Comment by irvinezhao** [comment]
目前调试已暂停，需要网络组提供测试网调试环境，网络组在搭建环境中 @TylerTang06
