### ISSUE TITLE
需要映射公网端口

### ISSUE THREAD

**Issue by DeliaDing123** [WeBankPartners/wecube-plugins-qcloud#36]
**描述您的需求**  
在VPC的某一个主机下，可能需要映射端口为公网端口，让外部可以访问。比如UM的UMAPP和SSO； SGS页面；CMC-CC等。PAAS 层组件大概有二十个左右的端口需要映射公网端口。

**Comment by brankbao** [comment]
插件补充LB创建销毁，监听器创建销毁，监听器后端bind主机的接口
