### ISSUE TITLE
qcloud插件修改register.xml和wecube2.0的注册文件一致

### ISSUE THREAD

**Issue by brankbao** [WeBankPartners/wecube-plugins-qcloud#92]
**描述您的需求**  
1.新建一个分支dev，该分支先不合并到master，避免改了之后wecube1.0用不了
2.按新的接口规范，修改register.xml和makefile。https://github.com/WeBankPartners/wecube-platform/blob/dev/wecube-wiki/docs/developer/WeCube-Platform%E6%8F%92%E4%BB%B6%E5%BC%80%E5%8F%91%E8%A7%84%E8%8C%83.md

**预期行为**  
对你预期会发生的事情的清晰而简洁的描述。 

**描述您考虑过的替代方案**  
对您考虑的替代解决方案进行清晰而简洁的描述。 

**附加**  
在此添加有关问题的任何其他上下文。

**Comment by TylerTang06** [comment]
已通过platform测试，并按最新要求更新了Makefile 以及register.xml.tpl。
